import './style.css';
import {MAX_TEMPLATE_ELEMENTS,CARD_PRESETS} from './config.js';
import {BUILTIN_TEMPLATES,DECORATIONS} from './templates.js';
import {createProject,createElement,addElement,serializeProject,parseProjectFile} from './model.js';
import {parseNameList,parseCsvRoster,matchPhotoFilename} from './importers.js';
import {History} from './history.js';import {resolveText,backgroundCss,backgroundSizeCss,decorationSvg,decorationSupportsText} from './renderer.js';
import {normalizeImage,fileToDataUrl} from './assets.js';import {saveRecovery,loadRecovery,clearRecovery} from './storage.js';
import {importCleverPdf} from './clever-import.js';import {rasterizeCard,pngZip,cardsPdf} from './export.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let project=createProject(),history=new History(project),selectedId=null,studentIndex=0,drag=null,saveTimer=null;
const stage=$('#cardStage');
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function safeName(s){return (s||'student-card').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'student-card'}
function currentStudent(){return project.students[studentIndex]||{fields:{Name:'Student Name'},photo:null,qr:null};}
function addDefinition(def){const el=addElement(project,createElement(def.type,structuredClone(def)));return el;}
function applyTemplate(key){const t=BUILTIN_TEMPLATES[key]||BUILTIN_TEMPLATES.blank;project.background={...project.background,...structuredClone(t.background)};for(const def of t.elements)addDefinition(def);}
function addDecoration(key){const d=DECORATIONS[key];if(!d)return;mutate(()=>{let last=null;for(const def of d.elements)last=addDefinition({...def,x:def.x??50,y:def.y??50});selectedId=last?.id||selectedId;});}

function snapshot(){project.meta.updated=new Date().toISOString();history.push(project);clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveRecovery(project).catch(console.warn),600);}
function setProject(p,{recovered=false}={}){project=p;history.reset(project);selectedId=null;studentIndex=0;render();if(recovered)$('#recoveryBanner').hidden=false;}
function render(){renderStage();renderProps();renderStudents();renderLayers();$('#elementCount').textContent=`${project.elements.length} / ${MAX_TEMPLATE_ELEMENTS}`;$('#bgType').value=project.background.type;$('#bgColor').value=project.background.color;$('#bgColor2').value=project.background.color2;$('#bgPattern').value=project.background.pattern||'none';}
function renderStudents(){const sel=$('#studentSelect');sel.innerHTML='';if(!project.students.length)sel.add(new Option('Sample Student','0'));else project.students.forEach((s,i)=>sel.add(new Option(s.fields.Name||`Student ${i+1}`,i)));sel.value=String(Math.min(studentIndex,Math.max(0,project.students.length-1)));renderRoster();}
function renderRoster(){const box=$('#rosterList');box.innerHTML=project.students.length?project.students.map((s,i)=>`<div class="roster-row"><strong>${escapeHtml(s.fields.Name||`Student ${i+1}`)}</strong> · ${Object.entries(s.fields).filter(([k])=>k!=='Name').map(([k,v])=>`${escapeHtml(k)}: ${escapeHtml(v)}`).join(' · ')} ${s.photo?'📷':''} ${s.qr?'▦':''}</div>`).join(''):'<div class="empty">No students yet.</div>';}
function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML;}
function renderStage(){const ratio=project.card.widthIn/project.card.heightIn,maxW=760,maxH=560;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}stage.style.width=`${w}px`;stage.style.height=`${h}px`;stage.style.background=backgroundCss(project.background);stage.style.backgroundSize=backgroundSizeCss(project.background);stage.innerHTML='';const safe=document.createElement('div');safe.className='safe-guide';const sx=project.card.safeIn/project.card.widthIn*100,sy=project.card.safeIn/project.card.heightIn*100;Object.assign(safe.style,{left:`${sx}%`,top:`${sy}%`,right:`${sx}%`,bottom:`${sy}%`,display:$('#safeToggle')?.checked?'block':'none'});stage.append(safe);for(const c of ['v','h']){const g=document.createElement('div');g.className=`center-guide ${c}`;stage.append(g)}const student=currentStudent();for(const el of [...project.elements].sort((a,b)=>a.z-b.z)){if(!el.visible)continue;const node=document.createElement('div');node.className=`card-element ${selectedId===el.id?'selected':''} ${el.locked?'locked':''}`;node.dataset.id=el.id;Object.assign(node.style,{left:`${el.x-el.w/2}%`,top:`${el.y-el.h/2}%`,width:`${el.w}%`,height:`${el.h}%`,transform:`rotate(${el.rotation}deg)`,opacity:el.opacity,zIndex:el.z,color:el.fill});let inner;if(['text','field'].includes(el.type)){const text=resolveText(el,student);if(el.curve){inner=document.createElement('div');inner.className='element-text curve-text';const bend=Number(el.curve),sweep=bend>0?1:0,arc=Math.max(10,100-Math.abs(bend)*.6),y=bend>0?75:25;inner.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><path id="p-${el.id}" d="M 5 ${y} Q 50 ${bend>0?arc:100-arc} 95 ${y}" fill="none"/><text text-anchor="middle" dominant-baseline="middle" fill="${el.fill}" stroke="${el.stroke}" stroke-width="${el.strokeWidth/3}" font-family="${el.fontFamily}" font-size="${Math.max(6,el.fontSize/3)}" font-weight="${el.fontWeight}"><textPath href="#p-${el.id}" startOffset="50%">${escapeHtml(text)}</textPath></text></svg>`;}else{inner=document.createElement('div');inner.className='element-text';inner.textContent=text;Object.assign(inner.style,{fontFamily:el.fontFamily,fontSize:`${el.fontSize}px`,fontWeight:el.fontWeight,fontStyle:el.fontStyle,color:el.fill,WebkitTextStroke:`${el.strokeWidth}px ${el.stroke}`,textShadow:el.shadow?`${el.shadowX}px ${el.shadowY}px ${el.shadowBlur}px ${el.shadowColor}`:'none'});}}
else if(el.type==='image'||el.type==='photo'){const src=el.type==='photo'?student.photo:el.src;if(src){inner=document.createElement('img');inner.className='image-inner';inner.src=src;inner.style.objectFit=el.fit;inner.style.borderRadius=`${el.borderRadius}%`;}else{inner=document.createElement('div');inner.className='placeholder';inner.textContent=el.type==='photo'?'Student Photo':'Image';}}
else if(el.type==='qr'){if(student.qrImage){inner=document.createElement('img');inner.className='image-inner';inner.src=student.qrImage;inner.style.objectFit='contain';inner.style.borderRadius=`${el.borderRadius}%`;}else{inner=document.createElement('div');inner.className='placeholder';inner.textContent=student.qr?'QR ✓':'Clever QR';}}
else if(el.type==='line'){inner=document.createElement('div');inner.className='line-inner';}
else if(el.type==='decoration'){inner=document.createElement('div');inner.className='decoration-inner';inner.innerHTML=decorationSvg(el);}
else{inner=document.createElement('div');inner.className='shape-inner';inner.style.borderRadius=`${el.borderRadius}%`;inner.style.color=el.fill;inner.style.border=`${el.borderWidth||0}px solid ${el.borderColor||'#17202a'}`;}
node.append(inner);if(selectedId===el.id&&!el.locked){const hdl=document.createElement('div');hdl.className='resize-handle';node.append(hdl)}stage.append(node)}checkOverflow();}
function checkOverflow(){let bad=false;stage.querySelectorAll('.element-text').forEach(n=>{if(n.scrollWidth>n.clientWidth+2||n.scrollHeight>n.clientHeight+2){n.parentElement.classList.add('overflowing');bad=true}});$('#overflowWarning').textContent=bad?'⚠ Some student text may overflow':'';}
function selected(){return project.elements.find(e=>e.id===selectedId)}
function renderProps(){const el=selected();$('#emptyProps').hidden=!!el;$('#props').hidden=!el;if(!el)return;$('#propType').textContent=el.type;const decorationText=el.type==='decoration'&&decorationSupportsText(el.decorationKind);$('#textRow').hidden=!(el.type==='text'||decorationText);$('#fieldRow').hidden=el.type!=='field';$('#fontRows').hidden=!(['text','field'].includes(el.type)||decorationText);$('#propText').value=el.text;$('#propField').innerHTML=project.fields.map(f=>`<option>${escapeHtml(f)}</option>`).join('');$('#propField').value=el.fieldKey;for(const [id,key,mul] of [['propW','w',1],['propH','h',1],['propRotation','rotation',1],['propOpacity','opacity',100],['propFontSize','fontSize',1],['propCurve','curve',1],['propStrokeWidth','strokeWidth',1],['propRadius','borderRadius',1],['propX','x',1],['propY','y',1]])$("#"+id).value=Math.round(el[key]*mul*10)/10;$('#propFill').value=el.fill;$('#propStroke').value=el.stroke;$('#propFont').value=el.fontFamily;$('#propWeight').value=String(el.fontWeight);$('#propShadow').checked=el.shadow;$('#lockBtn').textContent=el.locked?'Unlock':'Lock';$('#hideBtn').textContent=el.visible?'Hide':'Show';}
function renderLayers(){const sorted=[...project.elements].sort((a,b)=>b.z-a.z);$('#layers').innerHTML=sorted.map(e=>`<div class="layer ${e.id===selectedId?'selected':''}" data-layer="${e.id}"><span>${e.visible?'◉':'○'}</span><span>${escapeHtml(e.type==='field'?`{${e.fieldKey}}`:e.text||e.type)}</span>${e.locked?'<span>🔒</span>':''}</div>`).join('')}
function mutate(fn,{record=true}={}){fn();if(record)snapshot();render();}
function add(type){if(project.elements.length>=MAX_TEMPLATE_ELEMENTS)return alert(`This template already has ${MAX_TEMPLATE_ELEMENTS} elements.`);if(type==='image'){ $('#imageFile').click();return;}const defaults={field:{fieldKey:project.fields[0]||'Name',text:''},photo:{w:25,h:32},qr:{w:24,h:30},shape:{w:28,h:20,fill:'#93c5fd'},line:{w:35,h:5},text:{text:'New text'}};mutate(()=>{const el=addElement(project,createElement(type,{x:50,y:50,...defaults[type]}));selectedId=el.id;});}
$$('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));
stage.addEventListener('pointerdown',e=>{const node=e.target.closest('.card-element');if(!node){selectedId=null;render();return}selectedId=node.dataset.id;const el=selected();render();if(el.locked)return;const rect=stage.getBoundingClientRect(),start={x:e.clientX,y:e.clientY},orig={x:el.x,y:el.y,w:el.w,h:el.h};drag={id:el.id,start,orig,resize:e.target.classList.contains('resize-handle'),rect};stage.setPointerCapture?.(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!drag)return;const el=project.elements.find(x=>x.id===drag.id),dx=(e.clientX-drag.start.x)/drag.rect.width*100,dy=(e.clientY-drag.start.y)/drag.rect.height*100;if(drag.resize){el.w=Math.max(2,Math.min(100,drag.orig.w+dx));el.h=Math.max(2,Math.min(100,drag.orig.h+dy));}else{el.x=Math.max(el.w/2,Math.min(100-el.w/2,drag.orig.x+dx));el.y=Math.max(el.h/2,Math.min(100-el.h/2,drag.orig.y+dy));const nearX=Math.abs(el.x-50)<1,nearY=Math.abs(el.y-50)<1;if(nearX)el.x=50;if(nearY)el.y=50;}renderStage();});
stage.addEventListener('pointerup',()=>{if(drag){drag=null;snapshot();render()}});
const bindings={propText:['text',v=>v],propField:['fieldKey',v=>v],propW:['w',Number],propH:['h',Number],propRotation:['rotation',Number],propOpacity:['opacity',v=>Number(v)/100],propFill:['fill',v=>v],propFont:['fontFamily',v=>v],propFontSize:['fontSize',Number],propWeight:['fontWeight',Number],propCurve:['curve',Number],propStrokeWidth:['strokeWidth',Number],propStroke:['stroke',v=>v],propShadow:['shadow',(_,n)=>n.checked],propRadius:['borderRadius',Number],propX:['x',Number],propY:['y',Number]};
for(const [id,[key,conv]] of Object.entries(bindings)){const n=$('#'+id);n.addEventListener(n.type==='checkbox'?'change':'input',()=>{const el=selected();if(!el)return;el[key]=conv(n.value,n);renderStage();renderLayers();clearTimeout(n._t);n._t=setTimeout(snapshot,350)})}
$('#duplicateBtn').onclick=()=>{const el=selected();if(!el)return;mutate(()=>{const copy=addElement(project,createElement(el.type,{...Object.fromEntries(Object.entries(structuredClone(el)).filter(([k])=>k!=='id')),x:Math.min(95,el.x+3),y:Math.min(95,el.y+3)}));selectedId=copy.id})};$('#deleteBtn').onclick=()=>mutate(()=>{project.elements=project.elements.filter(e=>e.id!==selectedId);selectedId=null});$('#lockBtn').onclick=()=>mutate(()=>selected().locked=!selected().locked);$('#hideBtn').onclick=()=>mutate(()=>selected().visible=!selected().visible);$('#frontBtn').onclick=()=>mutate(()=>selected().z=Math.max(...project.elements.map(e=>e.z))+1);$('#backBtn').onclick=()=>mutate(()=>selected().z=Math.min(...project.elements.map(e=>e.z))-1);
$('#layers').onclick=e=>{const n=e.target.closest('[data-layer]');if(n){selectedId=n.dataset.layer;render()}};
$('#undoBtn').onclick=()=>{project=history.undo();selectedId=null;render()};$('#redoBtn').onclick=()=>{project=history.redo();selectedId=null;render()};
for(const id of ['bgType','bgColor','bgColor2'])$('#'+id).oninput=()=>mutate(()=>{project.background[id.replace('bg','').replace('Type','type').replace('Color2','color2').replace('Color','color')]=$('#'+id).value});
$('#bgPattern').onchange=()=>mutate(()=>{project.background.pattern=$('#bgPattern').value;project.background.type='pattern';});
$('#bgImageBtn').onclick=()=>$('#bgImageInput').click();$('#bgImageInput').onchange=async()=>{const f=$('#bgImageInput').files[0];if(f)mutate(()=>{}, {record:false}),project.background.image=await normalizeImage(f),project.background.type='image',snapshot(),render()};$('#safeToggle').onchange=renderStage;
$('#studentSelect').onchange=e=>{studentIndex=Number(e.target.value);renderStage()};$('#prevStudent').onclick=()=>{studentIndex=Math.max(0,studentIndex-1);render()};$('#nextStudent').onclick=()=>{studentIndex=Math.min(Math.max(0,project.students.length-1),studentIndex+1);render()};
$('#newBtn').onclick=()=>$('#newDialog').showModal();Object.entries(CARD_PRESETS).forEach(([k,v])=>$('#presetSelect').add(new Option(`${v.label} — ${v.widthIn} × ${v.heightIn} in`,k)));Object.entries(BUILTIN_TEMPLATES).forEach(([k,v])=>$('#templateSelect').add(new Option(`${v.category} — ${v.label}`,k)));Object.entries(DECORATIONS).forEach(([k,v])=>$('#decorationSelect').add(new Option(v.label,k)));$('#addDecorationBtn').onclick=()=>addDecoration($('#decorationSelect').value);
$('#createProjectBtn').onclick=e=>{e.preventDefault();const custom=$('input[name=sizeMode]:checked').value==='custom',p=custom?createProject({widthIn:Number($('#customW').value),heightIn:Number($('#customH').value)}):createProject(CARD_PRESETS[$('#presetSelect').value]);project=p;applyTemplate($('#templateSelect').value);history.reset(project);selectedId=null;studentIndex=0;clearRecovery();snapshot();render();$('#newDialog').close()};
$('#studentsBtn').onclick=()=>{$('#studentsDialog').showModal();renderRoster()};$('#closeStudents').onclick=()=>$('#studentsDialog').close();$$('[data-tab]').forEach(b=>b.onclick=()=>{const k=b.dataset.tab;$$('[id^=tab-]').forEach(x=>x.hidden=x.id!==`tab-${k}`);$$('[data-tab]').forEach(x=>x.classList.toggle('ghost',x!==b))});
$('#addNamesBtn').onclick=()=>{const s=parseNameList($('#namesText').value);if(!s.length)return;mutate(()=>{project.students.push(...s);project.fields=[...new Set([...project.fields,'Name'])]});$('#namesText').value=''};
$('#csvFile').onchange=async()=>{const f=$('#csvFile').files[0];if(!f)return;const r=parseCsvRoster(await f.text());$('#csvPreview').textContent=`Found ${r.students.length} students and fields: ${r.fields.join(', ')}`;mutate(()=>{project.students.push(...r.students);project.fields=[...new Set([...project.fields,...r.fields])]})};
$('#cleverFile').onchange=async()=>{const f=$('#cleverFile').files[0];if(!f)return;$('#cleverStatus').textContent='Reading PDF…';try{const r=await importCleverPdf(f,(n,t)=>$('#cleverStatus').textContent=`Reading page ${n} of ${t}…`);mutate(()=>{project.students.push(...r.students);project.fields=[...new Set([...project.fields,...r.fields])]});$('#cleverStatus').textContent=`Imported ${r.students.length} students.`}catch(err){$('#cleverStatus').textContent=`Could not import PDF: ${err.message}`}};
$('#photoFiles').onchange=async()=>{let matched=0,unmatched=[];for(const f of $('#photoFiles').files){const s=matchPhotoFilename(f.name,project.students);if(s){s.photo=await normalizeImage(f,1800,.88);matched++}else unmatched.push(f.name)}snapshot();render();$('#photoStatus').textContent=`Matched ${matched}. ${unmatched.length?`Unmatched: ${unmatched.join(', ')}`:'All photos matched.'}`};
$('#imageFile').onchange=async()=>{const f=$('#imageFile').files[0];if(!f)return;const src=await normalizeImage(f);mutate(()=>{const el=addElement(project,createElement('image',{x:50,y:50,w:30,h:30,src}));selectedId=el.id});$('#imageFile').value=''};
function exportProject(template=false){download(new Blob([serializeProject(project,{template})],{type:'application/json'}),`${safeName(project.name)}${template?'-template':'-project'}.json`)}$('#exportProjectBtn').onclick=()=>exportProject(false);$('#exportTemplateBtn').onclick=()=>exportProject(true);$('#recoveryExport').onclick=()=>exportProject(false);$('#importProjectBtn').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async()=>{try{const p=parseProjectFile(await $('#projectFile').files[0].text());if(p.type.includes('template')){p.students=project.students;p.fields=[...new Set([...project.fields,...p.fields])]}setProject(p);snapshot()}catch(e){alert(e.message)}};
$('#recoveryNew').onclick=()=>{if(confirm('Start a new project and replace the recovered work? Export first if you need to keep it.')){$('#recoveryBanner').hidden=true;clearRecovery();$('#newDialog').showModal()}};
$('#exportBtn').onclick=()=>{$('#copies').value=project.print.copies;$('#orientation').value=project.print.orientation;$('#exportDialog').showModal()};$('#closeExport').onclick=()=>$('#exportDialog').close();
async function renderCards(all=true){const old=studentIndex,copies=Math.max(1,Number($('#copies').value)||1),cards=[],students=project.students.length?project.students:[currentStudent()];project.print.copies=copies;project.print.orientation=$('#orientation').value;for(let i=0;i<students.length;i++){studentIndex=project.students.length?i:0;renderStage();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const dataUrl=await rasterizeCard(stage,project.card.widthIn,project.card.heightIn);for(let c=0;c<copies;c++)cards.push({name:`${safeName(students[i].fields.Name||`student-${i+1}`)}${copies>1?`-${c+1}`:''}.png`,dataUrl});if(!all)break}studentIndex=old;render();return cards}
$('#pngBtn').onclick=async()=>{setExportStatus('Rendering 300 DPI PNG…');try{const cards=await renderCards(false);download(new Blob([Uint8Array.from(atob(cards[0].dataUrl.split(',')[1]),c=>c.charCodeAt(0))],{type:'image/png'}),cards[0].name);setExportStatus('PNG ready.')}catch(e){setExportStatus(`Export failed: ${e.message}`)}};
$('#zipBtn').onclick=async()=>{setExportStatus('Rendering student cards…');try{const cards=await renderCards(true);download(await pngZip(cards),'student-cards.zip');setExportStatus(`ZIP ready with ${cards.length} card image(s).`)}catch(e){setExportStatus(`Export failed: ${e.message}`)}};
$('#pdfBtn').onclick=async()=>{setExportStatus('Rendering cards and assembling printable PDF…');try{const cards=await renderCards(true);download(await cardsPdf(cards,project),'student-cards-print.pdf');setExportStatus(`PDF ready with ${cards.length} card image(s).`)}catch(e){setExportStatus(`Export failed: ${e.message}`)}};function setExportStatus(s){$('#exportStatus').textContent=s}
(async()=>{try{const recovered=await loadRecovery(parseProjectFile);if(recovered)setProject(recovered,{recovered:true});else{render();$('#newDialog').showModal()}}catch{render();$('#newDialog').showModal()}})();
